language: ruby
cache: bundler

addons:
  postgresql: "9.4"

before_script:
  - createdb store_attribute_test
  - psql -U postgres -d store_attribute_test -c 'CREATE EXTENSION IF NOT EXISTS hstore;'

matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/rails5.gemfile
